// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dtp.type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Dwjk.Dtp {

  /// <summary>Holder for reflection information generated from dtp.type.proto</summary>
  public static partial class DtpTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for dtp.type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DtpTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5kdHAudHlwZS5wcm90bxIIZHdqay5kdHAq0QEKElJlc3BvbnNlU3RhdHVz",
            "Q29kZRIiCh5SRVNQT05TRV9TVEFUVVNfQ09ERV9VTkRFRklORUQQABIVChBS",
            "RVNQT05TRV9DT0RFX09LEMgBEh4KGVJFU1BPTlNFX0NPREVfQkFEX1JFUVVF",
            "U1QQkAMSHwoaUkVTUE9OU0VfQ09ERV9VTkFVVEhPUklaRUQQkQMSHAoXUkVT",
            "UE9OU0VfQ09ERV9GT1JCSURERU4QkwMSIQocUkVTUE9OU0VfQ09ERV9JTlRF",
            "Uk5BTF9FUlJPUhD0AypICghFeGNoYW5nZRIWChJFWENIQU5HRV9VTkRFRklO",
            "RUQQABIRCg1FWENIQU5HRV9TSF9BEAESEQoNRVhDSEFOR0VfU1pfQRACKjsK",
            "CU9yZGVyVHlwZRIYChRPUkRFUl9UWVBFX1VOREVGSU5FRBAAEhQKEE9SREVS",
            "X1RZUEVfTElNSVQQASqeAQoJT3JkZXJTaWRlEhgKFE9SREVSX1NJREVfVU5E",
            "RUZJTkVEEAASEgoOT1JERVJfU0lERV9CVVkQARITCg9PUkRFUl9TSURFX1NF",
            "TEwQAhIXChNPUkRFUl9TSURFX0NSRUFUSU9OEAsSGAoUT1JERVJfU0lERV9S",
            "RURFTVBUT04QDBIbChdPUkRFUl9TSURFX1JFVkVSU0VfUkVQTxAVKrECCgtP",
            "cmRlclN0YXR1cxIaChZPUkRFUl9TVEFUVVNfVU5ERUZJTkVEEAASGAoUT1JE",
            "RVJfU1RBVFVTX1BMQUNJTkcQARIXChNPUkRFUl9TVEFUVVNfUExBQ0VEEAIS",
            "HwobT1JERVJfU1RBVFVTX1BBUlRJQUxfRklMTEVEEAMSFwoTT1JERVJfU1RB",
            "VFVTX0ZJTExFRBAEEhsKF09SREVSX1NUQVRVU19DQU5DRUxMSU5HEAUSGgoW",
            "T1JERVJfU1RBVFVTX0NBTkNFTExFRBAGEiMKH09SREVSX1NUQVRVU19QQVJU",
            "SUFMX0NBTkNFTExJTkcQBxIiCh5PUkRFUl9TVEFUVVNfUEFSVElBTF9DQU5D",
            "RUxMRUQQCBIXChNPUkRFUl9TVEFUVVNfRkFJTEVEEAkqcgoKRmlsbFN0YXR1",
            "cxIZChVGSUxMX1NUQVRVU19VTkRFRklORUQQABIWChJGSUxMX1NUQVRVU19G",
            "SUxMRUQQARIZChVGSUxMX1NUQVRVU19DQU5DRUxMRUQQAhIWChJGSUxMX1NU",
            "QVRVU19GQUlMRUQQAyp+ChJRdWVyeU9yZGVyQ3JpdGVyaWESFAoQUVVFUllf",
            "T05MWV9PUkRFUhAAEiAKHFFVRVJZX09SREVSX0NBTl9CRV9DQU5DRUxMRUQQ",
            "ARIbChdRVUVSWV9PTkxZX0NBTkNFTF9PUkRFUhACEhMKD1FVRVJZX09SREVS",
            "X0FMTBADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Dwjk.Dtp.ResponseStatusCode), typeof(global::Dwjk.Dtp.Exchange), typeof(global::Dwjk.Dtp.OrderType), typeof(global::Dwjk.Dtp.OrderSide), typeof(global::Dwjk.Dtp.OrderStatus), typeof(global::Dwjk.Dtp.FillStatus), typeof(global::Dwjk.Dtp.QueryOrderCriteria), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ResponseStatusCode {
    [pbr::OriginalName("RESPONSE_STATUS_CODE_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 200:成功(服务器成功处理请求);
    /// </summary>
    [pbr::OriginalName("RESPONSE_CODE_OK")] ResponseCodeOk = 200,
    /// <summary>
    /// 400:请求错误(请求参数有误,参考message)
    /// </summary>
    [pbr::OriginalName("RESPONSE_CODE_BAD_REQUEST")] ResponseCodeBadRequest = 400,
    /// <summary>
    /// 401:未授权(需要登录)
    /// </summary>
    [pbr::OriginalName("RESPONSE_CODE_UNAUTHORIZED")] ResponseCodeUnauthorized = 401,
    /// <summary>
    /// 403:拒绝(违规, 柜台拒绝?)
    /// </summary>
    [pbr::OriginalName("RESPONSE_CODE_FORBIDDEN")] ResponseCodeForbidden = 403,
    /// <summary>
    /// 500:服务器内部错误
    /// </summary>
    [pbr::OriginalName("RESPONSE_CODE_INTERNAL_ERROR")] ResponseCodeInternalError = 500,
  }

  public enum Exchange {
    [pbr::OriginalName("EXCHANGE_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 沪A
    /// </summary>
    [pbr::OriginalName("EXCHANGE_SH_A")] ShA = 1,
    /// <summary>
    /// 深A
    /// </summary>
    [pbr::OriginalName("EXCHANGE_SZ_A")] SzA = 2,
  }

  public enum OrderType {
    [pbr::OriginalName("ORDER_TYPE_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 限价
    /// </summary>
    [pbr::OriginalName("ORDER_TYPE_LIMIT")] Limit = 1,
  }

  public enum OrderSide {
    [pbr::OriginalName("ORDER_SIDE_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 买入、新股申购
    /// </summary>
    [pbr::OriginalName("ORDER_SIDE_BUY")] Buy = 1,
    /// <summary>
    /// 卖出
    /// </summary>
    [pbr::OriginalName("ORDER_SIDE_SELL")] Sell = 2,
    /// <summary>
    /// ETF申购
    /// </summary>
    [pbr::OriginalName("ORDER_SIDE_CREATION")] Creation = 11,
    /// <summary>
    /// ETF赎回
    /// </summary>
    [pbr::OriginalName("ORDER_SIDE_REDEMPTON")] Redempton = 12,
    /// <summary>
    /// 质押式逆回购(国债逆回购)
    /// </summary>
    [pbr::OriginalName("ORDER_SIDE_REVERSE_REPO")] ReverseRepo = 21,
  }

  /// <summary>
  /// 该状态只体现交易所委托状态
  /// </summary>
  public enum OrderStatus {
    /// <summary>
    /// 柜台直接拒单时，不使用该状态，通过ReportHeader的code和message
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 正报: 交易所处理中(order_exchange_id已产生)
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_PLACING")] Placing = 1,
    /// <summary>
    /// 已报: 交易所已挂单
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_PLACED")] Placed = 2,
    /// <summary>
    /// 部分成交
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_PARTIAL_FILLED")] PartialFilled = 3,
    /// <summary>
    /// 全部成交
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_FILLED")] Filled = 4,
    /// <summary>
    /// 待撤
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_CANCELLING")] Cancelling = 5,
    /// <summary>
    /// 已撤
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_CANCELLED")] Cancelled = 6,
    /// <summary>
    /// 部分成交其余待撤
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_PARTIAL_CANCELLING")] PartialCancelling = 7,
    /// <summary>
    /// 部分成交其余已撤
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_PARTIAL_CANCELLED")] PartialCancelled = 8,
    /// <summary>
    /// 废单
    /// </summary>
    [pbr::OriginalName("ORDER_STATUS_FAILED")] Failed = 9,
  }

  public enum FillStatus {
    [pbr::OriginalName("FILL_STATUS_UNDEFINED")] Undefined = 0,
    /// <summary>
    /// 成交
    /// </summary>
    [pbr::OriginalName("FILL_STATUS_FILLED")] Filled = 1,
    /// <summary>
    /// 撤单成功
    /// </summary>
    [pbr::OriginalName("FILL_STATUS_CANCELLED")] Cancelled = 2,
    /// <summary>
    /// 废单
    /// </summary>
    [pbr::OriginalName("FILL_STATUS_FAILED")] Failed = 3,
  }

  public enum QueryOrderCriteria {
    /// <summary>
    /// 只查询委托（不包含撤单委托）
    /// </summary>
    [pbr::OriginalName("QUERY_ONLY_ORDER")] QueryOnlyOrder = 0,
    /// <summary>
    /// 只查可撤
    /// </summary>
    [pbr::OriginalName("QUERY_ORDER_CAN_BE_CANCELLED")] QueryOrderCanBeCancelled = 1,
    /// <summary>
    /// 只查询撤单委托   
    /// </summary>
    [pbr::OriginalName("QUERY_ONLY_CANCEL_ORDER")] QueryOnlyCancelOrder = 2,
    /// <summary>
    /// 查询全部类型
    /// </summary>
    [pbr::OriginalName("QUERY_ORDER_ALL")] QueryOrderAll = 3,
  }

  #endregion

}

#endregion Designer generated code
